workflow:
  name: 'NixOS Build Pipeline'
  auto_cancel:
    on_new_commit: interruptible
    on_job_failure: all

variables:
  CACHIX_CACHE_NAME:
    value: foxnet
    description: "Cachix.org binary cache where built objects will be pushed"


.cachix-build-host:
  stage: build
  image: docker.nix-community.org/nixpkgs/cachix-flakes
  interruptible: true
  before_script:
    - cachix use "$CACHIX_CACHE_NAME"
  script:
    - cachix watch-exec $CACHIX_CACHE_NAME -- nix build .#nixosConfigurations.$HOST.config.system.build.toplevel

build-loki:
  extends: .cachix-build-host
  variables:
    HOST: loki

build-burrow:
  extends: .cachix-build-host
  variables:
    HOST: burrow

build-hetzner-auth:
  extends: .cachix-build-host
  variables:
    HOST: hetzner-auth01
