workflow:
  name: 'NixOS Build Pipeline'

.build-cachix: &build-cachix
  image: docker.nix-community.org/nixpkgs/cachix-flakes
  before_script:
    - cachix use "$CACHIX_CACHE_NAME"
  script:
    - cachix watch-exec $CACHIX_CACHE_NAME -- nix build .#nixosConfigurations.$HOST.config.system.build.toplevel

build-loki:
  <<: *build-cachix
  variables:
    CACHIX_CACHE_NAME: foxnet
    HOST: loki

build-burrow:
  <<: *build-cachix
  variables:
    CACHIX_CACHE_NAME: foxnet
    HOST: burrow

build-hetzner-auth:
  <<: *build-cachix
  variables:
    CACHIX_CACHE_NAME: foxnet
    HOST: hetzner-auth01
