if vim.fn.exists('g:started_by_firenvim') == 1 then
    require('reyu.plugins.firenvim')
else
    require('gitsigns').setup()
    require('bufresize').setup()
    require('reyu.plugins.dap')
    require('reyu.plugins.fugitive')
    require('reyu.plugins.hydra')
    require('reyu.plugins.lualine')
    require('reyu.plugins.neo-tree')
    require('reyu.plugins.neotest')
    require('reyu.plugins.noice')
    require('reyu.plugins.notify')
    require('reyu.plugins.smart-splits')
    require('reyu.plugins.telescope')
    require('reyu.plugins.trouble')
    require('reyu.plugins.twilight')
    require('reyu.plugins.zen-mode')
end

require('reyu.plugins.cmp')
require('reyu.plugins.mini-nvim')
require('reyu.plugins.neoscroll')
require('reyu.plugins.refactoring')
require('reyu.plugins.treesitter')
require('reyu.plugins.ufo')
require('reyu.plugins.which-key')
