[hosts.loki]
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKnHNzgn/8WNjzUpjBJe3fWe7lFkvT8/v0nwEqvEtiOb"

[hosts.burrow]
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILYVDZQ6gxbDU4kpfLoA9qulQxMsPPT4E9xXdC7zSZUP"
