[loki]
publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP5RyYh6rTQJrsriGzONG4Dt0cb3Y3047KSFlylzm2zZ"
extraHostNames = [
  "loki.home.reyuzenfold.com"
]

[burrow]
publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMTxnWiWCer2tijhkTDA9RfxELHy0/HxY7zA8VgbnnFl"
extraHostNames = [
  "burrow.home.reyuzenfold.com",
  "100.83.149.127",
]

[hetzner-auth]
publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMLh/19bPHzmaJNswjqqt1aR/DwCdAsWRnjnCHQ/0VJc"
extraHostNames = [
  "auth.reyuzenfold.com"
]

[hetzner-ash-db]
publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICJ3ud5Xx9DsLPQs1c/cHk2tkclLQGE788OKC/1TQVBW"
extraHostNames = [
  "database.reyuzenfold.com",
  "database.ash.reyuzenfold.com"
]

[traveler]
publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFhbhOKgiYOV65i4DVIHjjeiDI6OSHc/6ci1nIb7j99v"
