name: build-hosts
on:
  pull_request:
  push:
jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install nix
        uses: cachix/install-nix-action@v20
      - name: Configure Cachix
        uses: cachix/cachix-action@v12
        with:
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          name: foxnet
      - name: Flake checks
        run: nix flake check
  build-hm-profile-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install nix
        uses: cachix/install-nix-action@v20
      - name: Configure Cachix
        uses: cachix/cachix-action@v12
        with:
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          name: foxnet
      - name: Build server home-manager profile
        run: nix build .#homeConfigurations.server.activationPackage
